### ISSUE TITLE
Which file to translate?

### ISSUE THREAD

**Issue by ChrisDorna** [strawbees/pxt-strawbees-microbit#1]
I want to translate the blocks into Dutch but cannot find the right file with the strings

**Comment by paulobarcelos** [comment]
Hi @ChrisDorna! Super cool that you would like to help us with the translations!

You will have to create a folder called `nl` inside the `_locales` folder (https://github.com/strawbees/pxt-robotic-inventions/tree/master/_locales). Then copy the files `_locales/Strawbees Robotic Inventions-strings.json` and `Strawbees Robotic Inventions-jsdoc-strings.json` into that folder. Then you can modify those files with the correct strings.

You can find more information about this technicality here https://makecode.com/extensions/localization in the the "Create the translations" section.

Please let me know if you need more help!

**Comment by ChrisDorna** [comment]
Hi Paulo,

I translated the files but cannot preview them.

This is what I did:

1.	I cloned everything to  <https://github.com/ChrisDorna/pxt-robotic-inventions> https://github.com/ChrisDorna/pxt-robotic-inventions
2.	Copied the two json files to the nl-directory
3.	Translated them
4.	Committed to master

In order to test:

1.	I opened makecode.microbit.org
2.	Added extension using this url:  <https://github.com/ChrisDorna/pxt-robotic-inventions> https://github.com/ChrisDorna/pxt-robotic-inventions

This didn’t work and I also replaced the two json-files in the _locales directory. Unfortunately this didn’t work (I tried English and Dutch/Nederlands

 Hope you can help me on this.

 
Thanks!

 

Chris Dorna

**Comment by paulobarcelos** [comment]
Hi Chris! Awesome effort into translating these, wow!

Hum, it really seems that testing the translations is a really complicated process in MakeCode. I never done it before, and was surprised by how many steps it take :(

I am not sure how tech savvy you are, but if you would like to have a try at it, please have a look at the guide here https://makecode.com/extensions/localization

One thing  you could try first however, is to also register the translation files in the `pxt.json`. Maybe that will make it work when you import it (I forgot to mention that step, sorry!).

Make sure the "files" entry look something like this:
```
"files": [
	"README.md",
	"main.ts",
	"_locales/nl/Strawbees Robotic Inventions-jsdoc-strings.json",
	"_locales/nl/Strawbees Robotic Inventions-strings.json"
]
```

If adding the entries to `pxt.json` doesn't solve it and you can't follow the microsoft instructions on how to test it, let me know and maybe I can temporarily commit it to master and ten we test it live. It's fair from ideal, but better than not honour your work due to complicated technicalities.

Replacing the original files won't work, that file only exists to help the translation - good try though!

**Comment by ChrisDorna** [comment]
Hi Paulo,

 

I still cannot get it working, perhaps the easiest way is the way you suggested before or that you prepare a testversion with the /nl path which I can clone, change and test.

 

Chris Dorna

 

 

CodeKids

Chris Dorna

chris@codekids.nl <mailto:chris@codekids.nl> 

www.codekids.nl <http://www.codekids.nl/> 

T: @CodeKidsNL <https://twitter.com/CodeKidsNL> 

+31 (0)6 - 50410541

 

 

 

Van: Paulo Barcelos <notifications@github.com> 
Verzonden: maandag 23 maart 2020 16:10
Aan: strawbees/pxt-robotic-inventions <pxt-robotic-inventions@noreply.github.com>
CC: Chris Dorna <chris@codekids.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [strawbees/pxt-robotic-inventions] Which file to translate? (#1)

 

Hi Chris! Awesome effort into translating these, wow!

Hum, it really seems that testing the translations is a really complicated process in MakeCode. I never done it before, and was surprised by how many steps it take :(

I am not sure how tech savvy you are, but if you would like to have a try at it, please have a look at the guide here https://makecode.com/extensions/localization

One thing you could try first however, is to also register the translation files in the pxt.json. Maybe that will make it work when you import it (I forgot to mention that step, sorry!).

Make sure the "files" entry look like this:

"files": [
        "README.md",
        "main.ts",
        "_locales/nl/Strawbees Robotic Inventions-jsdoc-strings.json",
        "_locales/nl/Strawbees Robotic Inventions-strings"
]

If adding the entries to pxt.json doesn't solve it and you can't follow the microsoft instructions on how to test it, let me know and maybe I can temporarily commit it to master and ten we test it live. It's fair from ideal, but better than not honour your work due to complicated technicalities.

Replacing the original files won't work, that file only exists to help the translation - good try though!

**Comment by paulobarcelos** [comment]
Hi Chris!

I've now just released a new version of the extension, where I've manually merged your translations. You can already see the result live, by going to https://makecode.microbit.org/ setting the language to Dutch and creating a new project with the latest version of the extension (v0.1.0).

*Very important to notice* that we changed all references to "NeoPixel" to RGB LED. I've also updated this in your translations, hopefully it makes sense in dutch.

I think the best way we can move forward with the translations if you want to fix or adjust something will be for you to re-fork the repo (since there have been a lot of underlying changes), and then work directly on the "_locales/nl" files and then just make a pull request, or simply notifying me here directly, then I can publish the changes.

**Comment by ChrisDorna** [comment]
Hi Paulo,

 

It works!



 

Thanks, I will check it while writing the review

 

Chris Dorna

 

Van: Paulo Barcelos <notifications@github.com> 
Verzonden: donderdag 7 mei 2020 12:00
Aan: strawbees/pxt-robotic-inventions <pxt-robotic-inventions@noreply.github.com>
CC: Chris Dorna <chris@codekids.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [strawbees/pxt-robotic-inventions] Which file to translate? (#1)

 

Hi Chris!

I've now just released a new version of the extension, where I've manually merged your translations. You can already see the result live, by going to https://makecode.microbit.org/ setting the language to Dutch and creating a new project with the latest version of the extension (v0.1.0).

Very important to notice that we changed all references to "NeoPixel" to RGB LED. I've also updated this in your translations, hopefully it makes sense in dutch.

I think the best way we can move forward with the translations if you want to fix or adjust something will be for you to re-fork the repo (since there have been a lot of underlying changes), and then work directly on the "_locales/nl" files and then just make a pull request, or simply notifying me here directly, then I can publish the changes.

**Comment by ChrisDorna** [comment]
Hi Paulo,

 

In the attached document you find the final changes for the Dutch translation. Please let me know when you finish the translation.

 

Chris Dorna

 

CodeKids

Chris Dorna

chris@codekids.nl <mailto:chris@codekids.nl> 

www.codekids.nl <http://www.codekids.nl/> 

T: @CodeKidsNL <https://twitter.com/CodeKidsNL> 

+31 (0)6 - 50410541

 

 

 

Van: chris@codekids.nl <chris@codekids.nl> 
Verzonden: dinsdag 12 mei 2020 07:58
Aan: 'strawbees/pxt-robotic-inventions' <reply@reply.github.com>
CC: chris@codekids.nl; Andreas Hoel <andreas.hoel@strawbees.com>
Onderwerp: RE: [strawbees/pxt-robotic-inventions] Which file to translate? (#1)

 

Hi Paulo,

 

It works!



 

Thanks, I will check it while writing the review

 

Chris Dorna

 

Van: Paulo Barcelos <notifications@github.com <mailto:notifications@github.com> > 
Verzonden: donderdag 7 mei 2020 12:00
Aan: strawbees/pxt-robotic-inventions <pxt-robotic-inventions@noreply.github.com <mailto:pxt-robotic-inventions@noreply.github.com> >
CC: Chris Dorna <chris@codekids.nl <mailto:chris@codekids.nl> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Onderwerp: Re: [strawbees/pxt-robotic-inventions] Which file to translate? (#1)

 

Hi Chris!

I've now just released a new version of the extension, where I've manually merged your translations. You can already see the result live, by going to https://makecode.microbit.org/ setting the language to Dutch and creating a new project with the latest version of the extension (v0.1.0).

Very important to notice that we changed all references to "NeoPixel" to RGB LED. I've also updated this in your translations, hopefully it makes sense in dutch.

I think the best way we can move forward with the translations if you want to fix or adjust something will be for you to re-fork the repo (since there have been a lot of underlying changes), and then work directly on the "_locales/nl" files and then just make a pull request, or simply notifying me here directly, then I can publish the changes.

**Comment by paulobarcelos** [comment]
Did you forget to attach the document? I don't see any file...

**Comment by ChrisDorna** [comment]
Hi Paulo,

 

That is because Github Mail does not accept attachments. You cab download the file here:  <https://we.tl/t-E6hSI78vtQ> https://we.tl/t-E6hSI78vtQ 

 

Chris Dorna

 

 

CodeKids

Chris Dorna

chris@codekids.nl <mailto:chris@codekids.nl> 

www.codekids.nl <http://www.codekids.nl/> 

T: @CodeKidsNL <https://twitter.com/CodeKidsNL> 

+31 (0)6 - 50410541

 

 

 

Van: Paulo Barcelos <notifications@github.com> 
Verzonden: dinsdag 12 mei 2020 23:26
Aan: strawbees/pxt-robotic-inventions <pxt-robotic-inventions@noreply.github.com>
CC: Chris Dorna <chris@codekids.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [strawbees/pxt-robotic-inventions] Which file to translate? (#1)

 

Did you forget to attach the document? I don't see any file...

**Comment by paulobarcelos** [comment]
Closing this, as we have now published the NL translations.
